add User and Film service, exception handler
dsivanov5372/java-filmorate pull request #2
Opened 2022-10-14 20:45 UTC by dsivanov5372

2022-10-15 09:42 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addUser(@Valid @RequestBody User user) throws ValidationException {
Если отправить такой запрос
{
	"id":1,
	"name":"nameFilm2",
	"description":"film Description",
	"releaseDate":"2012-04-23T18:25:43.511Z",
	"duration":22,
	"login": "userLogin",
	"email":"test@test.ru"
}
то в ответ приходит странное сообщение:
404 - {
	"error": null
}

2022-10-15 09:44 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @lombok.Builder
Что-то с импортами. Аннотация должна быть просто @Data, @Builder

2022-10-15 09:48 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +                                        ));
На строке 47,48,49,51 предлагаю поменять местами параметрами, т.к. сперва идет expected value,  потом идет actual

2022-10-15 09:49 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +                                        ));
строка 57 - конкатенация строк в цикле - плохая практика так делать, т.к. будет желание так делать и дальше в боевом коде

2022-10-15 09:49 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        assertEquals(film.getUsersLikes().contains(user.getId()), true);
Используй assertTrue

2022-10-15 09:50 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +
Строка 94 можно написать короче
ValidationException exception = assertThrows(ValidationException.class, () -> controller.addFilm(film));

2022-10-15 09:51 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    public void checkOrderOfFilmsWhenGetMostPopular(ArrayList<Film> films, int size)
Для чего кидать эксепшн в тестах? Этот эксепшн никогда не кидается тут к тому же

2022-10-15 09:51 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        films.stream().forEach((film) -> {
Можно написать проще
for (Film film : films) {
            try {
                controller.addFilm(film);
            } catch (ValidationException e) {
                e.printStackTrace();
            }
        }

2022-10-15 09:52 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    @ParameterizedTest
параметризованные тесты это круто.

2022-10-15 09:52 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Совсем немного замечаний. Поправь, пожалуйста.

2022-10-15 22:07 UTC, dsivanov5372 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addUser(@Valid @RequestBody User user) throws ValidationException {
У меня вообще такая ошибка
{
	"error": "Cannot invoke \"java.time.chrono.ChronoLocalDate.toEpochDay()\" because \"other\" is null"
}

2022-10-17 09:19 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2022-10-17 09:20 UTC, EvgenyKoptubenko commented
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-10-18 16:47 UTC, merged