add database
dsivanov5372/java-filmorate pull request #5
Opened 2022-11-14 23:41 UTC by dsivanov5372

2022-11-15 21:08 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDao.java
>      Film getFilmById(long id) throws RuntimeException;
Не нужно писать что кидается RuntimeException, т.к. это unchecked exception. Лучше перейти на какой-то свой эксепшен, если на него завязана логика.

2022-11-15 21:13 UTC, EvgenyKoptubenko commented on README.md
> +![pic1](./pics/diagram.png)
таблица лайков на диаграмме прилипла к genres, а стрелочки должны идти к films, users

2022-11-15 21:18 UTC, EvgenyKoptubenko commented
Если передать неверные запрос на добавление пользователя, то возвращается не обработанный ответ
{
	"error": "Cannot invoke \"java.time.chrono.ChronoLocalDate.toEpochDay()\" because \"other\" is null"
}

2022-11-15 21:18 UTC, EvgenyKoptubenko commented
Работа сделана очень хорошо. Замечаний практически нет.

2022-11-15 21:19 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Замечаний практически нет.

2022-11-15 22:00 UTC, dsivanov5372 commented
> Если передать неверные запрос на добавление пользователя, то возвращается не обработанный ответ
> {
> "error": "Cannot invoke "java.time.chrono.ChronoLocalDate.toEpochDay()" because "other" is null"
> }

Честно говоря, тут я не знаю, как это исправить, я уже однажды вам писал с вопросом, как это исправить, мы так ни к чему и не пришли) Но зато за это время я узнал, как создавать строку из повторяющихся символов без цикла)

2022-11-16 06:44 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2022-11-16 07:26 UTC, merged